### ISSUE TITLE
plpython3u extension missing?

### ISSUE THREAD

**Issue by marioot** [PostgresApp/PostgresApp#207]
When trying:
CREATE EXTENSION plpython3u;  
ERROR:  could not open extension control file "/Applications/Postgres.app/Contents/Versions/9.3/share/postgresql/extension/plpython3u.control": No such file or directory

Versions:
OS X 10.9.4
Postgres 9.3.5.0

**Comment by mickeydonkey** [comment]
the postgresql document says ["To make both variants of PL/Python available in one installation, the source tree has to be configured and built twice." ](http://www.postgresql.org/docs/9.5/static/plpython-python23.html)

**Comment by kellington** [comment]
Any update on this?  Python 3 seems to be gaining traction and 2016 might be time to make it available.
Thanks

**Comment by anthonydb** [comment]
Wondering if there's any thought of advancing this?

**Comment by jakob** [comment]
Building Postgres.app with support for Python3 would probably take a bit of effort, but it should be doable. However, there is one question we first need to answer:

**Which Python should plpython3u link with?**

For Python 2, the answer is trivial: we link with the system-provided Python, which is guaranteed to work everywhere. Since macOS doesn't ship with Python 3, we can't do that for version 3.

That leaves us with 2 possibilities:

1. Include our own version of Python 3 to link against
2. Link against Python installed by a different installation method

I think we can immediately rule out the first option. It would take a lot of space, and I would effectively become a Python packager as well -- something I'd like to avoid.

The second option requires that we choose a specific Python distribution to link against. The obvious choice would be to link against the official version from python.org. It would probably be a bit inconvenient for people who have installed Python 3 with a different method like homebrew.

Other potential issues:
- What happens when a new version of Python is released? plpython3 will need to link against a specific version of Python.
- How will people find out about the requirements to use plpython3u? Trying to use it without linked libraries available will probably spit out an incomprehensible error message.

**Comment by alitrack** [comment]
there is a solution now,
[How to enable plpython3u extension on Postgre.app](http://blog.rubypdf.com/2019/06/29/how-to-enable-plpython3u-extension-on-postgre-app/) 
with the help of conda-forge.

**Comment by tbussmann** [comment]
In Postgres.App, we build PostgreSQL against different versions of Python 3 from python.org since PostgreSQL 13. Instructions for users can be found [in the docs](https://postgresapp.com/documentation/plpython.html). Apple finally removed Python 2.7 in macOS 12.3, so `plpython2u` of PostgreSQL 11 and 12 are not longer working on Monterey, Ventura and Sonoma. Given the age of these versions, this combination seems to be unlikely and users should soon migrate to a newer version of PostgreSQL anyhow.
Ideas for (further) improving the python support are discussed mainly in #551, so I'm going to close this issue.
