### ISSUE TITLE
The App icon in the menu bar should be toggable

### ISSUE THREAD

**Issue by gespinha** [PostgresApp/PostgresApp#220]
Hi there,

The elephant icon in the menu bar should be toggable, it shouldn't be necessary in crowded menu bars. There should be an indicator within the app welcome modal, that shows if Postgres is running or not.

Is this planned for the near future?

Thanks in advance ;)

**Comment by vdhub** [comment]
Hello, any idea how to put this in a LaunchDaemon  plist file ? i`ve tried al the options but unfortunately no luck . 

Thanks

**Comment by sebbean** [comment]
@mattt download / install / use an app so that i don't have to see a completely unrelated other app? 

I think the idea here is that almost all things that live in your menu bar have the option of not living in the menu bar in the preferences. 

99% of the time postgres is running juuuust fine.. so that lil elephant up there isn't doing a hell of a lot for me.

Mysql for instance has a panel that lives in the System preferences pane: (Works like shit but hey.. that's another story)
<img width="780" alt="screen shot 2015-11-23 at 3 22 28 pm" src="https://cloud.githubusercontent.com/assets/423997/11330873/0448abf2-91f6-11e5-85ac-1ef8e4c482b3.png">

**Comment by jakob** [comment]
@sebbean I agree that it would be nice if Postgres.app had an option to hide the menu bar status item.

However, at the moment, the UI is only accessible through the status item menu. Adding an option to hide this item would require significant changes to the UI.

I have some ideas for an improved UI, which would include an option to hide the status bar icon, but unfortunately I just can't afford to spend two or three weeks on Postgres.app right now, especially considering that this is a minor feature, for which there are workarounds available (see above).

**Comment by sebbean** [comment]
ha, @jakob i didn't even think of that.

no worries man. thanks for this Elephant.app!
