### ISSUE TITLE
Add /Applications/Postgres.app/Contents/Versions/9.4/bin/ to /etc/paths.d/postgresapp when moving to /Applications/ dir

### ISSUE THREAD

**Issue by rslnx** [PostgresApp/PostgresApp#259]
You can search for "mac postgresapp psycopg2 pg_config" on StackOverflow and you'll see that's a very popular problem: doing `pip install psycopg2` fails because it can't find `pg_config`. Common answer is "add the dir containing pg_config to your $PATH". Could installer create new file `/etc/paths.d/postgresapp` and add `/Applications/Postgres.app/Contents/Versions/9.4/bin/` to it? It would make things much easier.

**Comment by jakob** [comment]
Hey, this sounds like a great idea. I've considered automatically adding paths to the $PATH variable in the users profile, but I was sceptical about changing `~/.profile` or `~/.bash_profile`.

I never knew about `/etc/paths.d` and `path_helper`; this looks like a clean solution! Do you know if path_helper also works in alternative shells (like zsh or fish)?

**Comment by khrf** [comment]
`path_helper` surely will work fine with `zsh`, but I don't know about `fish` as I don't have it installed. `zsh` sources `/etc/profile` and `path_helper` produces sh-compatible output that is compatible with `zsh`.

**Comment by tbussmann** [comment]
I really like that elegant method. When implementing, please note not to end the path with an `/` as the automatic detection of corresponding man pages would not work otherwise, as I just learned ;)
Till this is done by the app itself, users of Postgres.app can easily create the file with the following command:

`sudo /bin/bash -c "echo /Applications/Postgres.app/Contents/Versions/9.4/bin > /etc/paths.d/postgresapp"`

**Comment by sethk** [comment]
Maybe you could use `Versions/latest` in the path as well? Or put a checkbox into the UI? That way you wouldn't have to clobber the file later in case the user wants to change it.

**Comment by jakob** [comment]
I've now updated the installation instruction on the homepage to add a file to `/etc/paths.d`. I hope this fixes the issue for most people.

I don't want Postgres.app to create this file automatically, since it would need an administrator password, and people might be wary of giving admin permissions to Postgres.app. When you execute the command manually, you know what's going on :)
