### ISSUE TITLE
nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by kikar** [PostgresApp/PostgresApp#266]
Just updated app to 9.4.2 and can't connect anymore with the same string to my AWS DB.
String used is `psql -h serverName.rds.amazonaws.com -d databaseName -U userName` and it gives me the error: `psql: could not translate host name 'same address as before' to address: nodename nor servname provided, or not known`.
Even tried prefixing hostname with http:// but still not working

**Comment by jakob** [comment]
Looks like psql can't resolve the host name. Prefixing with http:// won't help.

Did you try `nslookup serverName.rds.amazonaws.com` to see if host name lookup works in general?

Also, since Yoesemite seems to have so many issues with discoveryd, did you try if restarting your Mac fixes the name resolution problems?

**Comment by kikar** [comment]
Sorry, was another type of issue with my server. Thank you
