### ISSUE TITLE
Suggestion: add a restart button in the context bar

### ISSUE THREAD

**Issue by Alexis-benoist** [PostgresApp/PostgresApp#274]
Hey,

Postgres.app is great, I use it almost every day!

I need to create and drop the database and to run my tests.

Sometimes the previous test doesn't stop and i can't drop the DB when I relaunch them. So the test waits for the DB to finish, and I need to stop and restart the DB.

Do you guys think that it would be a good idea to add a restart button on the menu bar?

Alternatively, is there a way to do that (restart the DB) from the command line?

Cheers,
Alexis.

**Comment by jakob** [comment]
We had a similar request some time ago and decided to keep it simple. You can quit & reopen Postgres.app to restart the server.

You can try this command to restart the server from the command line

    pg_ctl restart -w -D "/Users/USERNAME/Library/Application Support/Postgres/var-9.4" -m fast

You need to use fast mode because otherwise the server will wait for all connections to terminate before restarting.

An even easier solution would probably be to just open Activity Monitor and kill the backend that is executing your tests. No need to restart the server.

Or you could use the [`pg_terminate_backend(pid)`](http://www.postgresql.org/docs/current/static/functions-admin.html) function to kill the test backend cleanly from psql.

In both cases, use a command like `select * from pg_stat_activity` to find the pid (process id) of the backend that's executing the tests.

**Comment by Alexis-benoist** [comment]
Thanks for the fast answer! I will look into that!

PS: PG commanger is great :)
