### ISSUE TITLE
include a stable symlink to the latest binaries

### ISSUE THREAD

**Issue by tbussmann** [PostgresApp/PostgresApp#277]
Since some versions the binaries are located in a directory that corresponds the major version of PostgreSQL. While this is a good thing, it brings the problem that in any script that refers such a binary, the path mentioned need to be changed from version to version, e.g. `/Applications/Postgres.app/Contents/Versions/9.4/bin/pg_dump` to `/Applications/Postgres.app/Contents/Versions/9.5/bin/pg_dump`. This wouldn't be necessary if there would be a symlink to the latest (only) version of the binaries at a stable path, for example by `ln -s ./9.4 /Applications/Postgres.app/Contents/Versions/latest`. With this, you can always use a path like `/Applications/Postgres.app/Contents/Versions/latest/bin/pg_dump` in your scripts. 
Please consider to include such a link in the distribution.

**Comment by jakob** [comment]
I think I wanted to include something like this originally, but there was some issue with including a symlink inside the app package... I'll have a look.

**Comment by diwu1989** [comment]
what if you made the app itself create that symlink during the startup? it would write to its own folder if the symlink isn't there

**Comment by jakob** [comment]
I've implemented this in 9.5.0.0. I've also changed the docs to recommend setting the path to `/Applications/Postgres.app/Contents/Versions/latest/bin`

However, this won't fix all issues. If something links against libpq (eg. the ruby pg gem), you'll still need to recompile after updating, since it will likely point to the absolute path :(

At least you don't need to update your shell scripts.
