### ISSUE TITLE
Network traffic question

### ISSUE THREAD

**Issue by ivanakimov** [PostgresApp/PostgresApp#282]
Hi, sorry this is not an issue, just a question. I noticed in my network tab, `postgres` has the 2nd largest network usage, right after `Skype`. I'm curious as to what it is (especially since I haven't used postgres and it's just been sitting in the background)?

![postgres](https://cloud.githubusercontent.com/assets/1404596/9726778/6221c802-55ac-11e5-9bc8-b8dbb7dc0ef8.png)

**Comment by jakob** [comment]
I have a hunch that it may be the statistics collector. As far as I understand, the different postgres processes use a shared UDP port for communicating statistics. This would make sense because the number of sent bytes matches the received bytes.

These connections show up in activity monitor because they go through the network stack; but they don't actually leave your computer so they won't use up your data plan if you have a metered connection.

**Comment by ivanakimov** [comment]
That makes sense. Looks like someone else also stumbled on the same issue: http://superuser.com/questions/856752/why-is-postgres-sending-network-traffic-on-osx

It was just so surprising to see how much it was sending. Thanks for your response. I'll close the issue.
