### ISSUE TITLE
Unspecified version of PLV8

### ISSUE THREAD

**Issue by alexandertakacs** [PostgresApp/PostgresApp#295]
The build doesn't set a specific version of PLV8 but just picks the latest one which is potentially unstable. This also means it could suddenly break compatibility with a given version of postgres.

I just hit an issue where I'm not sure which build of PLV8 I'm actually using because it depends on what time the build was made for the binary distribution.

**Comment by jakob** [comment]
When I wrote the build script, plv8 had no explicit versioning, and was more or less abandoned. One major issue was it didn't support modern versions of v8. However I still wanted to include it since it is such a valuable extension.

Is plv8 actively developed again now? Do they have proper versions now?

**Comment by alexandertakacs** [comment]
The latest release happened may 2015, they seems to have had proper releases in github for some time (with varying intensity). It's even one of few extensions installed by default om AWS RDS so I guess it's fairly popular.

**Comment by alexandertakacs** [comment]
https://github.com/plv8/plv8/releases

**Comment by jakob** [comment]
OK, this looks interesting. I wasn't aware they moved to Github (my build script still clones from Google Code)

Next time I build Postgres.app, I'll switch to using released versions instead of building from master. Maybe they even support linking to a newer libv8 now! Thanks for letting me know about this!

**Comment by alexandertakacs** [comment]
I'm happy I could contribute. Thanks for making this very useful piece of software!

Seems at least they have tested it with v8 4.3.x :)

**Comment by jakob** [comment]
I switched to building a specific v8 version now.

Unfortunately I wasn't able to get a recent version of v8 to build, so we're still stuck with v8 3.18

**Comment by jakob** [comment]
I switched to building a specific version of plv8 now.

Unfortunately I wasn't able to get a recent version of v8 to build, so we're still stuck with v8 3.18

**Comment by jakob** [comment]
I switched to building a specific version of plv8 now.

Unfortunately I wasn't able to get a recent version of v8 to build, so we're still stuck with v8 3.18

**Comment by ozum** [comment]
Hi,

I couldn't manage to build plv8 previously, now I built it as **static**. I installed plv8 2.0.0-dev (latest version as of this message) on PostgresApp 9.5.1.0 on MacBook Pro OS X El Capitan 10.11.3 smoothly using steps below in case anyone interested.

- Downloaded from [https://github.com/plv8/plv8](https://github.com/plv8/plv8).
- Uncompressed zip file
- In a terminal, changed into created directory and executed following commands:
- `$ make static` - Takes lots of time. (I couldn't compile without `static` previously.)
- `$ make install`
- Restarted PostgresApp and execute following SQL command on a database.
- `CREATE EXTENSION plv8`

Checked plv8 version and it's working now.

**Comment by mauritslamers** [comment]
Is there any ETA on when a newer version of plv8 would land in the PostgresApp?

**Comment by jakob** [comment]
@mauritslamers Last time I tried, I couldn't get a newer version of plv8 to compile on macOS 10.10 (which we use for building Postgres.app). The biggest issue was building recent versions of libv8. 

Apparently, the only way to build libv8 is to download gigabytes of sources for Google's in-house build system -- but in the end it failed on my machine, and I couldn't figure out why.

If someone could show me how to build libv8 on macOS 10.10 with Xcode 7, I could deliver a new version of plv8.

**Comment by mauritslamers** [comment]
@jakob I asked because @ozum stated he managed to build it. However, in the mean time of me posting the question, I have noticed that there are a few complicating external factors. 

My main reason for asking was to be able to use ES6 features, which would come with version 1.5 of plv8. It turns out however that on my deployment platform of choice Ubuntu, libv8 has been stuck on version 3.14 for over two years now with little indication that that is going to change anytime soon. As any ES6 features are only available from libv8 version 4 and up, this is going to be out of my reach for now as it doesn't make much sense to try to develop using something that cannot be deployed (yet). Thanks for the quick answer!

**Comment by jakob** [comment]
Presumably the Ubuntu folks have been running into the same issues as I have (Google changed the build system around that time, so it's become pretty difficult to build recent versions of libv8)

**Comment by hsyed** [comment]
It is way too limiting to have 1.4.8 these days, 1.5.3 provides a lot of required baseline features. Could we make tracking the RDS features provided by plv8 a priority or would it be possible to bundle multiple versions ?

**Comment by jakob** [comment]
Since Google switched the build system for Chrome, it has become extremely difficult to build libv8, and as far as I've read, they are about to switch the build system again.

In order to build new versions of plv8, I need a recent binary of the libv8 library. Ideally it should be compatible with OS X 10.7 thru 10.12, like all the other binaries bundled with Postgres.app.

If someone finds a way to build that, I'll update the version of plv8. Presumably it would be best to update the plv8 version when Postgres 10 is released later this year. Bundling multiple versions of plv8 with PostgreSQL 9.6 is something I'd like to avoid.

I've been experimenting with building libv8 with Macports in a macOS 10.7 VM. That might result in a portable binary, but I haven't had success yet.

**Comment by mauritslamers** [comment]
@jakob If you have a binary libv8, it should not be very difficult to include it in the .app. It most probably needs editing of the linking information. However, having libv8 built for linux is the biggest issue. It seems Google switched to something called GN:  https://github.com/v8/v8/wiki/Building%20with%20GN

**Comment by deem0n** [comment]
Hi all, 

It seems that we can easily have plv8 2.x now. On the Mac you can install v8 with `brew install v8` which is installed in binary form:

`/usr/local/Cellar/v8/5.1.281.47: 32 files, 748.5MB`

Can we have it included in PostgreSQL 10 Beta 2 build ?

`/usr/local/Cellar/v8/5.1.281.47/lib/libv8.dylib = 13942300 bytes`

**Comment by nileshtrivedi** [comment]
Would really love to see this fixed. Running Postgres 10.1 but plv8.version = 1.4.8 which misses many basic things like Uint8Array.

**Comment by nileshtrivedi** [comment]
I asked V8 devs: https://twitter.com/bmeurer/status/960584003148505088

**Comment by JerrySievert** [comment]
noticed you're not shipping plv8 as part of the most recent release, due to build issues.

if you care to outline any build issues, I'm happy to help.  little known fact, most plv8 work occurs in macOS.

**Comment by JerrySievert** [comment]
as an aside, do not use `brew` or `macports` versions of `libv8`, they are very far behind, suffer from spectre/meltdown issues, and often-times plain do not work with `plv8`, which is currently using 6.4.388.40.  just like `node`, you should be using the shipped `v8`, as `v8` no longer will compile into a shared library (by design).  simply running `make` from `plv8` will download and compile the correct version of `v8`.

**Comment by jakob** [comment]
@JerrySievert Thanks for reaching out!

The biggest problem in the past was getting a recent version of libv8 that's backward compatible to 10.7, but we've decided to no longer support these old systems any more for PostgreSQL 11. We're planning to raise our deployment target to 10.10.

I'll try building v8 via plv8! I'll get back to you if there are any issues.

**Comment by JerrySievert** [comment]
if you decide to reverse that, I may have an old Mac mini running something as old as 10.7 sitting around that I can probably get going.

not sure why v8 itself wouldn't compile on it (since it downloads its own compilers), but plv8 might not due to possibly using a few newer c++ features.

**Comment by jakob** [comment]
Latest versions of ICU also don’t build anymore with deployment target 10.7, so plv8 isn’t the only reason.

**Comment by JerrySievert** [comment]
yeah, icu on `v8` is a bit of a pain - I will note that it is disabled by default during build of `plv8`, if you need it on, there are notes in the docs on how to configure it via `make`: https://plv8.github.io/#building-with-icu

there are also some notes in `contrib` for it.

**Comment by jakob** [comment]
Since I raised the deployment target for PostgreSQL 11 to macOS 10.12, I was able to build plv8 and v8. So Postgres.app now includes plv8 2.3.8, and I hope I can now always keep it on the newest version.

Unfortunately, I was not able to get plv8 to build with ICU, so I disabled ICU just like you mentioned.

Also, the v8 docs state that 10.12 is required, so I'm not sure if it is possible to build recent plv8 on older versions of macOS. 

I'm happy it works now, and I hope nothing breaks. The v8 build system is so complicated that I have no clue where I would even begin debugging issues...

I'm sad that we can no longer support older versions of macOS, but at least we have up to date versions of plv8 now!

**Comment by JerrySievert** [comment]
@jakob fyi, if you do need help debugging the v8 build process, I've managed to get pretty good at it (go figure).  just open an issue on plv8, and I can likely help guide you through it - plv8 _is_ developed on macOS these days after all.

**Comment by jakob** [comment]
@JerrySievert I never realised you are the developer behind plv8! Thanks for your offer! At the moment plv8 seems to build fine (except that I couldn't get v8 to build with ICU).

Do you happen to know if it is possible to build v8 with an externally provided ICU? I assume not, since it seems to download and build its own version of ICU. But it would be sweet if PostgreSQL & plv8 would use the same version of ICU...

**Comment by JerrySievert** [comment]
you can specify `use_system_icu=1` during the v8 build configuration, but that means either building v8 by hand, or modifying the `Makefile`.

unfortunately, I don't remember if the required icu library is actually the system icu on macOS though.
