### ISSUE TITLE
Did I install Postgress properly

### ISSUE THREAD

**Issue by RaffiSapire** [PostgresApp/PostgresApp#300]
Hi there,

I'm new to all this so - I just installed postgress. I am trying to configure the $PATH. Can someone please tell me if I did this correctly? 

http://postgresapp.com/documentation/cli-tools.html

```bash
Raphaelas-MacBook-Air:~ raphaelasapire$ ~/.bash_profile: export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin
-bash: /Users/raphaelasapire/.bash_profile:: No such file or directory
Raphaelas-MacBook-Air:~ raphaelasapire$ which psql
/Applications/Postgres.app/Contents/Versions/9.4/bin/psql
Raphaelas-MacBook-Air:~ raphaelasapire$ 
```

Thanks,

Raphaela

**Comment by jakob** [comment]
Hi Raphaela,

That's not quite correct. `.bash_profile` is a configuration file that you need to edit, or create if it doesn't exist yet.

Here's how you can do that in the Terminal:

1. Type `cd ~` to switch to your home directory
2. Type `ls -a` to see if you already have a file named `.bash_profile`  or `.profile` (you can use either)
3. If the file does not exist, type `touch .bash_profile` to create it.
4. Now type `open -a TextEdit .bash_profile` to open the file in TextEdit
5. Now add the line `export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin` at the end of the file.
6. Save the file, close all Terminal windows, open a new window and type `which psql` to see if it worked.

Explanation: .bash_profile is a configuration file that is executed every time you open a new Terminal window. The export command changes the PATH environment variable so that bash (the program running in Terminal) knows where to find all the PostgreSQL programs like psql.

Does this help?

**Comment by jakob** [comment]
I'm closing this issue now. If you have any further questions, feel free to add comments or reopen it at any time!
