### ISSUE TITLE
Notes on upgrade instructions

### ISSUE THREAD

**Issue by Themanwithoutaplan** [PostgresApp/PostgresApp#305]
Thanks very much for the detailed instructions on using `pg_uprade` between versions.  I hit a couple of problems following them:
- different locale between new and old clusters (easy enough to fix) so I had delete and start again
- after migrating the data and starting the Postgres.app I got a message telling me that Postgres was corrupt and did I want to delete it. It seems that removing the older version from `Contents/Versions` needs to be done for this to work properly. Presumably there is some kind of checksum in the package.
- upgrading really ought to become the preferred way of moving between versions. The instructions are already very good and could form the basis of an automatic script.

**Comment by jakob** [comment]
The improved `pg_upgrade` instructions were provided by @jace (see issue #241).

Could you elaborate why you think that using pg_upgrade should be preferred over dump/restore?

In my opinion the latter (dump/restore) should be preferred, since it is easier to understand, doesn't require mucking with the internals of Postgres.app, and is way more flexible. You can use dump/restore also for backups, for transferring to a different machine, or to a server etc.

**Comment by jace** [comment]
I got hit by the encoding issue when upgrading on a Linux box. We need a single line amendment: `initdb -E UTF8 …`

**Comment by jakob** [comment]
@jace Oh, right. I added the default encoding parameters that Postgres.app also uses when creating a cluster:
https://github.com/PostgresApp/postgresapp.github.io/commit/2b498d88cf1b2f4c911e4a9579395e25e1e93f6d

**Comment by jakob** [comment]
Sorry, I just accidentally closed the issue by clicking the wrong button.

So, is there any input whether pg_upgrade is better than dump/restore?

**Comment by Themanwithoutaplan** [comment]
It seems natural for me for programs that get installed like this to offer to upgrade an existing installation. `pg_dump & pg_restore` can be considerable hurdles to jump if you have either a lot of dbs or any big ones: I have a local one that is about 10 GB – does that make it big?

**Comment by jace** [comment]
I agree. With `pg_dump` and `pg_restore` I have to make a list of databases to migrate and worry about missing something. With `pg_upgrade` I only have to look at _one_ status message at the end of it to confirm it worked without glitches.

**Comment by jakob** [comment]
Maybe I should change the pg_dump/restore instructions to use pg_dump_all, which would make it significantly shorter.

**Comment by Themanwithoutaplan** [comment]
What would be the advantage of that over pg_upgrade? In any case the arguments for or against using pg_upgrade shouldn't really be about the size of the DB unless this is really quantified.

BTW it's my own fault but I forgot to migrate the changes I'd made in postgresql.conf when upgrading. This should definitely be covered in the docs.

**Comment by jakob** [comment]
There are several reasons why I prefer pg_dump/pg_restore:

1) pg_dump/pg_restore does not require modifying Postgres.app

2) Teaching people how to use pg_dump is much more useful than pg_upgrade. While pg_upgrade is only useful for upgrading, pg_dump is useful for data transfer in general.

3) Customizing the upgrade process with pg_dump is trivial: you can just edit the dump files with a text editor. This also means that fixing errors is easier.

So I think that pg_dump should be preferred, unless you don't have enough space on your hard drive for the dump and the new database. This size restriction hard to quantify, since it is not easy to predict how big the dump will be.

**Comment by Themanwithoutaplan** [comment]
I'm not against teaching people about the Postgres utilities, far from it. But I think the process of upgrading Postgres.app can be improved with less manual intervention. Anyone doing much with a server is not likely to want to use Postgres.app in the first place and have their own scripts in place for testing and migrating.

Whether you use pg_upgrade or pg_dumpall may be a matter of preference. Disk space required will be at least 3 times that of the existing cluster. This kind of information can be given to the user. And, as I said above, migrating the config is at least as important.

So, how about an optional check for updates with a link to a relevant in the docs?

**Comment by jakob** [comment]
The new docs now show multiple options side by side. We're not planning to write an automatic data directory update script right now, since that is hard to get right in the general case, and if it fails, data might be lost.

Postgres.app 2.0 can now run multiple versions simultaneously, so it is no longer necessary to update all your stuff at once; you can keep using your old data with an old version, while running a new server with the latest release of PostgreSQL.

I'm closing this issue now. If you have any other suggestions related to this, please open a new issue.
