### ISSUE TITLE
PG-strom integration planned?

### ISSUE THREAD

**Issue by stenerikbjorling** [PostgresApp/PostgresApp#333]
Are there any plans to integrate a working PG-strom implementation in PostgresApp? This would allow Postgres to use the GPUs in the computer to speed up certain operations - transparently. Would be nice to have this extension working in the PostgresApp install.

**Comment by jakob** [comment]
I don't think that PGStrom is a good fit for Postgres.app. First of all, it requires the CUDA toolkit, which is a massive download (1GB). Obviously we can't include that in Postgres.app. But even if users were required to download that separately, I would need to download it and keep it up to date on my build machine; something I'd like to avoid (building Postgres.app is already complicated enough). And it seems that there are different versions of CUDA toolkit for every version of macOS; Postgres.app is a single binary that's (mostly) compatible with OS X 10.7-10.12.

Furthermore, the goal of Postgres.app is to make it easy to get started in the common case. I'm not sure what kind of workloads PGStrom is used for, but I presume that it is mainly useful for specialized applications.

Of course; I might be wrong. If many people request PGStrom, and it turns out that this is useful for popular applications, I'm willing to reconsider.

**Comment by jakob** [comment]
I'm closing this issue since we got no further feedback. It seems that interest for PGStrom isn't that big.

Feel free to reopen this issue at any time if you can provide a compelling use case.
