### ISSUE TITLE
gin_trgm_ops does not exist for access method "gin"

### ISSUE THREAD

**Issue by beckmx** [PostgresApp/PostgresApp#335]
Hello, I have been working on a project that is shared by several members, and lately I cannot use my postgress installation for this problem:

PG::UndefinedObject: ERROR:  operator class "gin_trgm_ops" does not exist for access method "gin"

Any ideas?

**Comment by tbussmann** [comment]
seems you don't have the pg_trgm extension installed in the database in question. Try `CREATE EXTENSION pg_trgm;`

**Comment by sailing** [comment]
Even with the extension installed, I still see this, on 9.4.9.1

**Comment by sailing** [comment]
@beckmx, to clarify what @tbussmann responded, you need to ```\c``` to the database in question before running ```CREATE EXTENSION pg_trgm;```

By default PostgresApp has you on your personal DB.

**Comment by quocgfy** [comment]
Works great for me. thanks!

**Comment by jakob** [comment]
Glad it worked! Since there's nothing to do for us here, I'm closing this issue.

**Comment by leandropadua** [comment]
Thanks for the solution. That worked partially for me. The full solution was to apply it to every schema by adding the schema pg_catalog to the end of it:
`create extension pg_trgm with schema pg_catalog;`

**Comment by jhoval** [comment]
It worked for me as well, with another extension related to GIN (intarray). I needed to select the schema as @leandropadua mentioned.

`create extension intarray with schema nameOfMySchema`

**Comment by jiapei100** [comment]
> 

Thank you so much.... Seriously thank you ....

**Comment by jiapei100** [comment]
> @beckmx, to clarify what @tbussmann responded, you need to `\c` to the database in question before running `CREATE EXTENSION pg_trgm;`
> 
> By default PostgresApp has you on your personal DB.


Thank you so much....

**Comment by Que2701** [comment]
@tbussmann works for me

**Comment by rulasmarmol** [comment]
In my case I already had the extension installed, but I created a new schema and it was not working with the new schema, so I had to drop the extension and create a new one specifying the schema and that work.

**Comment by lauksas** [comment]
In my case, some other script created the extension in a non-standard schema, thus the gin_trgm_ops was not being found.
I issued `ALTER EXTENSION pg_trgm SET SCHEMA pg_catalog;` to my script and it worked.
Hope that helps someone.

**Comment by alistairreynolds** [comment]
In my case it was a bit different. I was restoring using a dump file of a separate schema (not including the `public` schema), so when restoring into the target database where I'd already had the extension created, it could only create it on the public schema, not the new one. And I couldn't create the extension on the _target_ schema because it hadn't been created yet (slightly chicken-egg).

Only real way around it was to re-create the extension on the target schema after it had finished reimporting, then re-adding the indexes

**Comment by tbussmann** [comment]
The key factor here is that the extension either needs to be installed in [a schema which is in your `search_path`](https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATH) _or_ you need to schema qualify the calls to the extension's functions.

You can view the `search_path` with `SHOW search_path;` - it defaults to `"$user", public`.

@rodraen: you installed the extension to the `public` schema, which is in the default `search_path` (this is the default, you don't need to specify `WITH SCHEMA public`). In the call to the `similarity` function, you specify a schema `pg_trgm` which apparently does not exist. You should be able to simply use it like `select similarity(ow_fullname, 'test') from licontract;`.

Please note that Schema names starting with `pg_` are reserved, so if you want to install the extension to a specific schema, you need to name it otherwise. Further, it is not considered a [_secure schema usage pattern_](https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATTERNS) to give untrusted users write access to schema `public` - this is reflected by the default access rights in PostgreSQL 15 and later.
