### ISSUE TITLE
OpenStreetMap and some Extenstions

### ISSUE THREAD

**Issue by senturk** [PostgresApp/PostgresApp#337]
Following extensions are required for the OpenStreetMap Database, which could be part of you great distribution:
- postgis_sfcgal.control
- address_standardizer.control
- address_standardizer_data_us.control

Does it make sense to include them?

**Comment by jakob** [comment]
I did some research. Both of these come with PostGIS, but are only built when dependencies are available.

address_sanitizer definitely makes sense; since OS X ships with libpcre that should be built. But building against libpcre isn't as easy as I'd hoped, since some header files are missing.

postgis_sfcgal support requires sfcgal; I guess that is a bigger library; I'm not sure I want to include that with Postgres.app, since the package is already pretty big.

**Comment by jakob** [comment]
I found a way to build PostGIS with address_sanitizer, and uploaded a new release:
https://github.com/PostgresApp/PostgresApp/releases/

The new release is just 300kB larger, so that sounds reasonable.

Future versions will also include address_sanitizer.

I'm not sure if this will help you since you also need postgis_sfcgal. I'll have a look at sfcgal some other time.

**Comment by senturk** [comment]
thank you!

but you are right. i although need postgis_sfcgal. 

But since i don't like to create test builds on my machine, i will postpone this 'tryout' until i have a gain a plain machine to try on, or until you find a time to include it - of course only if it makes sense for your distribution.

till then i'm very happy to use your new distribution, which really is quite helpful and handy.

**Comment by saerdnaer** [comment]
Sitenote: if you need postgis_sfcgal you can try to install postgis via homebrew.

**Comment by DzhonPeppe** [comment]
Hi Guys,
I am new here and a relatively new Swift Developer. However, I am very anxious and excited to contribute and learn as much as possible.
 With that said, is anyone still working on this (it looks like it's been a while since the last comment)? Can I assist in either way (if someone is working on this topic, just tell me how I can help)? Or, is there perhaps a better task that a newbie like me can take on?
I look forward to your answers and getting started!
Dzhon

**Comment by timoruohomaki** [comment]
Is there any news or workaround on how to include posts_sfcgal? It's quite important for all the PostGIS work. There was a posting on the issue from 2015 so it's not uncommon to have it missing from packages but patching an existing installation manually later on is a bit tricky. https://postgis.net/2015/10/25/postgis_sfcgal_extension/

**Comment by axelson** [comment]
Any update on this? Even though the Postgres.app claims to support PostGIS trying to enable PostGIS as specified on the PostGIS homepage will fail:
```
-- Enable PostGIS (as of 3.0 contains just geometry/geography)
CREATE EXTENSION postgis;
-- enable raster support (for 3+)
CREATE EXTENSION postgis_raster;
-- Enable Topology
CREATE EXTENSION postgis_topology;
-- Enable PostGIS Advanced 3D
-- and other geoprocessing algorithms
-- sfcgal not available with all distributions
CREATE EXTENSION postgis_sfcgal;
-- fuzzy matching needed for Tiger
CREATE EXTENSION fuzzystrmatch;
-- rule based standardizer
CREATE EXTENSION address_standardizer;
-- example rule data set
CREATE EXTENSION address_standardizer_data_us;
-- Enable US Tiger Geocoder
CREATE EXTENSION postgis_tiger_geocoder;
```
With errors like:
```
ERROR:  could not open extension control file "/Applications/Postgres.app/Contents/Versions/14/share/postgresql/extension/postgis_sfcgal.control": No such file or directory
CREATE EXTENSION
ERROR:  could not open extension control file "/Applications/Postgres.app/Contents/Versions/14/share/postgresql/extension/address_standardizer.control": No such file or directory
ERROR:  could not open extension control file "/Applications/Postgres.app/Contents/Versions/14/share/postgresql/extension/address_standardizer_data_us.control": No such file or directory
CREATE EXTENSION
data_library=# CREATE EXTENSION address_standardizer;
ERROR:  could not open extension control file "/Applications/Postgres.app/Contents/Versions/14/share/postgresql/extension/address_standardizer.control": No such file or directory
```
Maybe at least the Postgres.app homepage could be updated to say that it only has partial support for PostGIS.

**Comment by axelson** [comment]
Great, thanks for the response! I'm glad to know that it is intended to be supported because I really like the ease of use of Postgres.app :+1:

**Comment by jakob** [comment]
Postgres.app 2.6.2 now ships with postgis_sfcgal!
