### ISSUE TITLE
FATAL:  lock file "/tmp/.s.PGSQL.5432.lock" already exists

### ISSUE THREAD

**Issue by sayuri399** [PostgresApp/PostgresApp#361]
I had this error and startup server fails.

I tried to delete all the folders and app several times. However still getting the same error.

Smo, can help me?

"FATAL:  lock file "/tmp/.s.PGSQL.5432.lock" already exists
HINT:  Is another postmaster (PID 293) using socket file "/tmp/.s.PGSQL.5432"?
LOG:  database system is shut down"

**Comment by tongh18** [comment]
hi, is there a solution for this?
Thanks

**Comment by jakob** [comment]
@tongh18 I think there are two possible issues:

1) You already have a PostgreSQL server running on your Mac

2) Your computer crashed and the lockfile is pointing to a different process, so PostgreSQL thinks the server is still running.


To see what's going on, first print the contents of the lockfile:

```bash
cat /tmp/.s.PGSQL.5432.lock
```

You should get something that looks like this:

```
77252
/Users/jakob/Library/Application Support/Postgres/var-14
1660205923
5432
/tmp
```

The first line is the pid of the PostgreSQL server. To check if that is indeed a PostgreSQL server, do something like this: 

```bash
ps -p 77252
```

Then you'll see which process that is. If that process is postgres, then you need to shut down that other server. The second file in the lock file shows the data directory, so that should help figuring out where that other server is running.

If that process is something other than postgres, then the lockfile is stale and you can just delete it with rm, and then you should be able to start the PostgreSQL server.
