### ISSUE TITLE
Applications won't start on OSX 10.6.1 under Macports

### ISSUE THREAD

**Issue by Rob2015** [PostgresApp/PostgresApp#366]
Hi,
I installed https://github.com/macports/macports-ports/tree/master/databases/postgresql96 under macports under OSX 10.6.1. When I start the Postgres.app I get the message psql: FATAL:  role "******" does not exist.
How do solve this issue?
Many thanks in advance.

Rob2015

**Comment by jakob** [comment]
Postgres.app does not run on macOS 10.6.1, and you don't need Postgres.app if you use MacPorts to install PostgreSQL.

The error you quoted usually happens when you connect with the wrong username. Make sure to specify the right user name. For example, if you are using psql, try `psql -U postgres`

**Comment by jakob** [comment]
Also, it could mean that the user is missing on the PostgreSQL server. Postgres.app executes the commands `createuser -U postgres -s $USER` and `createdb $USER` to make sure that a default user and database exist.

I'm closing this issue now, since it doesn't look like this is actually related to Postgres.app. (You can still ask further questions -- but in general I'd recommend to ask on the PostgreSQL mailing lists or on the IRC channel for topics not specifically related to Postgres.app)
