### ISSUE TITLE
How to quit PostgresApp and postgres from command line?

### ISSUE THREAD

**Issue by MW3000** [PostgresApp/PostgresApp#378]
In earlier versions,
`osascript -e 'quit app "Postgres"'`
would quit the PostgresApp and all postgres processes.

Since version 2, it seems, `osascript -e 'quit app "Postgres"'` and also `osascript -e 'quit app "PostgresMenuHelper"'`, quit the respective apps, but leave the postgres processes running.

How can I properly quit PostgresApp from the command line?   
Is it safe to just `pkill postgres` after quitting the apps via `osascript`?

**Comment by jakob** [comment]
pkill sends the TERM signal by default, which will cause a more or less graceful shutdown.

It's enough to signal just the postmaster (you can find its pid from the postmaster.pid file in the data directory). It will signal child processes to quit as required. You can also use the `pg_ctl` program instead of `kill`.

However, if you just want to quit the server, and don't care if existing connections are forcefully closed, `pkill postgres` will do no harm.

See more info here: https://www.postgresql.org/docs/current/static/server-shutdown.html

Also, if you just want to stop the servers, you don't need to quit the UI apps. They won't restart server processes automatically.

**Comment by jakob** [comment]
Also, `pkill postgres Postgres` or even simpler `pkill -i postgres` is probably the quickest way to kill everything. (no need to bother with Apple Script)

**Comment by MW3000** [comment]
Thank you.
