### ISSUE TITLE
Start PG at system startup?

### ISSUE THREAD

**Issue by 9mm** [PostgresApp/PostgresApp#386]
It seems I can let the server get started automatically when I run PG, but how can I get PG itself to run at system startup so I basically never have to worry about it?

**Comment by jakob** [comment]
By default, Postgres.app configures itself to start automatically when you login. It does this by creating a "launch agent" file at the following path:
`~/Library/Launch Agents/com.postgresapp.Postgres2LoginHelper.plist`.

You can also disable or reenable autostart in the Postgres.app preferences.

Note that Postgres.app only starts after you log in. If you want your servers to start at system startup, before you login, I recommend to create a launch daemon that uses pg_ctl to start the server. However, that is an advanced topic, and I don't know much about the details, so I can't really help there.

**Comment by 9mm** [comment]
I think I found a bug then. If the 'hide icon from menu bar' is checked, then it never starts when the computer starts. If I uncheck that box then it works (by starting both the app and the server).

**Comment by jakob** [comment]
Are you sure that it's broken? When you uncheck the "show in menu bar" setting, Postgres.app should start the servers invisibly in the background on login.

**Comment by 9mm** [comment]
Here's what I did to reproduce:

Make sure settings look like this:

![image](https://cloud.githubusercontent.com/assets/1386207/24296764/cd80b74e-1076-11e7-859d-b991b43ec2ea.png)

![image](https://cloud.githubusercontent.com/assets/1386207/24296746/c0be025a-1076-11e7-8ca4-4651a6d77fe2.png)

![image](https://cloud.githubusercontent.com/assets/1386207/24296757/c87b2824-1076-11e7-9cf5-9211dbfb3b90.png)

![image](https://cloud.githubusercontent.com/assets/1386207/24296786/e36b8bd8-1076-11e7-89d0-d90ecb80474e.png)

1. Restart computer and make sure 'open windows' is unchecked.
2. Try to connect to PG. Doesn't connect
3. Change the 1 setting to show it in menu bar
4. Restart again
5. I can now connect

**Comment by 9mm** [comment]
I've flip-flopped it 4 times now to make sure there was nothing "residual" or any weirdness which might have 'carried over'. The checkbox definitely affects its ability to restart

**Comment by 9mm** [comment]
![image](https://cloud.githubusercontent.com/assets/1386207/24296949/72edd982-1077-11e7-8063-94c74a33f97b.png)

**Comment by jakob** [comment]
Thanks! I'll see if I can reproduce the issue!

**Comment by 9mm** [comment]
Any luck reproducing by chance?

**Comment by jakob** [comment]
@9mm I was able to reproduce it, and I think I found the problem. It's a race condition.

The PostgresLoginHelper executable starts the servers asynchronously in the background. When the menu item is enabled, it also launches the PostgresMenuHelper executable (which displays the menu item).

When the menu item is disabled, PostgresLoginHelper terminates immediately after dispatching the start command, so it terminates before the start command has completed.

The simplest solution would be to add a `sleep(10)` instruction before terminating the login helper (since it doesn't really matter how long it runs).

A cleaner solution would be to start the servers synchronously -- that would also eliminate race conditions when eg. multiple servers are configured to use the same port (by guaranteeing that the first server wins).

Thanks for your bug report!

**Comment by jakob** [comment]
Hey! I've now rewritten the login helper to start the PostgreSQL server sunchronously (ie. wait until it has actually started before exiting)

In my testing, this now works as expected.

Could you download this build and see if it works for you?
https://eggerapps-downloads.s3.amazonaws.com/Postgres-2.0.2-21.dmg


Best regards,
Jakob

**Comment by 9mm** [comment]
Awesome, will do

**Comment by 9mm** [comment]
works!
