### ISSUE TITLE
Postgres.app main window is not hidden at startup

### ISSUE THREAD

**Issue by mokolabs** [PostgresApp/PostgresApp#407]
In the previous version of Postgres.app, the main app window stayed hidden on restart unless it was launched from the menu bar.

But, in the latest version of Posgtres.app, on restart, the main app window is not hidden -- even if the currently logged in user has checked "Hide" for Postgres.app in the Login Items list in the Users & Groups preference page in System Preferences.

![screen shot 2017-09-28 at 6 29 37 pm](https://user-images.githubusercontent.com/444/30997202-fec220a2-a47a-11e7-9371-5232bd2df5b4.png)

In macOS, the normal expectation for menu bar apps is that their windows stay hidden until the menu bar app is accessed from the menu bar by the user -- even after restarting.

So... it would be nice to restore this feature to how it worked in the last version. :)

Thoughts?

**Comment by mokolabs** [comment]
This one was my fault, so I'm going to close it.

I mistakenly added Postgres app to my Login Items. But since Postgres already loads itself on login by default, this was duplicative and unnecessary -- and that's what was causing the main window app to appear on reboot.

**Comment by jakob** [comment]
Postgres.app doesn't use a login items, because we couldn't get them to work reliably.

Instead, Postgres.app creates a launch agent at the following path:
`~/Library/LaunchAgents/com.postgresapp.Postgres2LoginHelper.plist`

This launch agent automatically starts a helper app (not the main app) on login.

Please don't delete this file manually, and please don't add Postgres.app to your login items.

If you'd like to configure whether Postgres.app starts automatically, please go to "Preferences…" in Postgres.app, and uncheck "Automatically start at login". This will delete the launch agent file automatically.

**Comment by mokolabs** [comment]
Sorry for the confusion, Jakob. I realized the Login Item was not needed a few minutes after I opened this issue, but I forgot to post an update.

But, even after removing the Login Item, I still see the main window for Postgres.app when I reboot.

The `Automatically start Postgres on Login` option is enabled in preferences within Postgres.app. I have also verified that the launch agent is installed and working correctly.

So... I reboot my machine. Postgres.app is launched. And the main window is visible.

Is that a bug? Or is that the current intended behavior?

I'm hoping that I can launch Postgres.app on restart -- without ever seeing the main window -- as Postgres.app worked in previous versions (for me, at least).

That's the point I was trying to make above. For menu bar apps, they should really stay hidden until the user interacts with them.

**Comment by mokolabs** [comment]
Okay... I did some more digging and I think this problem is unique to my setup.

I have a multi-monitor machine and I'm using the[ Hocus Focus](http://hocusfoc.us) utility to auto-hide app windows after a certain period of time.

On reboot, Postgres.app launches and does it thing. But so does Hocus Focus. So I suspect that Hocus Focus inadvertently opens the main window for Postgres.app when it launches -- only to later hide it 30 seconds later (which is the default setting for when to hide an app).

I've test Postgres.app on other machines which don't have Hocus Focus installed and it's working fine there, so I'm going to close this issue.

Sorry for the trouble! :)

**Comment by ProfStringer** [comment]
Here we are 3 years later, and this is still a problem in Catalina.  The postgres helper (Version 2.3.5 (79)) launches every single login and I cannot get it to go away.  Unchecking "automatically start Postgres at login" has no effect.  Trying to add the app to my logins and having it start hidden doesn't work.  There it is every single time.  It's annoying and I would love it to go away.

Note that there are no launch agents for com.postgresapp in either ~/Library/LaunchAgents/ or in /[my drive]/Library/LaunchAgents.  The only instance I found of the com.postgresapp.Postgres2LoginHelper.plist I found was in /Applications/Postgres/Contents/Resources/com.postgresapp.Postgres2LoginHelper.plist.

Please help me make this go away.

**Comment by jakob** [comment]
@ProfStringer This issue was closed 3 years ago. Your issue sounds like something unrelated. Could you open a new issue and explain exactly what is happening? The Postgres Login Helper and Menu Helper apps have no UI (except a menu bar icon for the latter), so it's unclear to me what exactly you are seeing.

**Comment by ProfStringer** [comment]
Identical description and behavior to the original ticket 3 years ago.  But, yes, I can open a new ticket.

On Jun 5, 2020, at 11:01 AM, Jakob Egger <notifications@github.com<mailto:notifications@github.com>> wrote:



@ProfStringer<https://github.com/ProfStringer> This issue was closed 3 years ago. Your issue sounds like something unrelated. Could you open a new issue and explain exactly what is happening? The Postgres Login Helper and Menu Helper apps have no UI (except a menu bar icon for the latter), so it's unclear to me what exactly you are seeing.
