### ISSUE TITLE
Postgres 10.0 has inconsistent paths

### ISSUE THREAD

**Issue by craiglabenz** [PostgresApp/PostgresApp#417]
Postgres 10's binaries are located here:

```
/Applications/Postgres.app/Contents/Versions/10/bin/
```

whereas Postgres 10's data directory is located here:

```
~/Library/Application\ Support/Postgres/var-10.0/
```

For scripting setup, it would be nice to see the binaries also located inside a `10.0` folder.

Thanks so much for this awesome app! Happy paid user of this and Postico :smile:

**Comment by jakob** [comment]
The name of the binary path and the default data directory should match, and they should both be `10` rather than `10.0`.

Here's why:

The PostgreSQL project changed their version numbering scheme with version 10. Previously, the scheme was MAJOR.MAJOR.BUGFIX; now the version number scheme is MAJOR.BUGFIX.

So previously, incompatibilities version 9.5 and 9.6 where incompatible, whereas 9.6.1 and 9.6.2 weere compatible.

With the new scheme, version 10 and 11 are incompatible, whereas 10.0 and 10.1 are compatible.

(Compatible means that the data format doesn't change, and the dynamic library version doesn't change)

That's why we also changed the name of the bin paths and the name of the data directory.

**However, it looks like your data directory doesn't have the new pattern**. Did you choose this name yourself, or did Postgres.app create that directory? If it's the latter, this is a bug. In my testing, Postgres.app creates the data directory with the correct name. Looking through the code, I really don't  see how Postgres.app would create a directory named "10.0". Could you confirm that Postgres.app really creates a dir with the wrong name?

**Comment by craiglabenz** [comment]
Thanks for the explanation on that naming convention switch. I assumed `10.0` would be the standard, but your backstory was helpful.

I removed and re-added the Postgres 10 server from my sidebar to confirm what Postgres.app's default path was and saw that it is well formed according to your above description. Given the confusion that you clarified above, I must have seen `var-10` back when I first installed a PG 10 server, assumed it was a bug, and added a `.0` to the end.

Thanks so much for the response! Postico and Postgres.app make the transition for a long-time MySQL POW to Postgres so much less intimidating :smile:
