### ISSUE TITLE
https://postgresapp.com/ gives SSL_ERROR_BAD_CERT_DOMAIN in firefox

### ISSUE THREAD

**Issue by globalbusybee** [PostgresApp/PostgresApp#450]
postgresapp.com uses an invalid security certificate. The certificate is only valid for the following names: www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by captproton** [comment]
Yup, I got the same thing.  Ditto for Safari 11.1.

**Comment by jakob** [comment]
Sorry about that. It should work again now.

We used Cloudflare for HTTPS support, and since Github pages now supports HTTPS natively, I turned Cloudflare off on Friday morning. I expected the switchover to be seamless, but for some reason Github started serving the site with the github.com certificate. Most users were initially not affected, since the nameservers had a long TTL, so most users were still served by Cloudflare.

After a few emails back and forth with Github support, they finally "nudged" the SSL generation process on Saturday evening, and it looks like it works now.

Sorry for the inconvenience. I guess we can't expect instant support and zero downtime on a free service.

**Comment by jakob** [comment]
@captproton @globalbusybee Could you confirm that the website loads with the correct cert again now?

**Comment by globalbusybee** [comment]
@jakob,

The site now loads using a valid certificate.

Thanks for the quick fix. It will enhance confidence accessing the site and usage of Postgres.app.

Please note the certificate will expire on 24 August 2018.

**Comment by jakob** [comment]
@globalbusybee Lets Encrypt certificates are always valid for only 3 months. Usually Lets Encrypt certificates are renewed automatically every two months.

**Comment by globalbusybee** [comment]
@jakob 
I like the Postgres.app, keep up the good work
