### ISSUE TITLE
Error installing Ruby pg gem with Postgres.app 11 compile error .rvm

### ISSUE THREAD

**Issue by RustyHack** [PostgresApp/PostgresApp#487]
I'm trying to integrate Postgres.app with a Rails project. At one time it was working. I can't install the latest pg gem 1.1.3. I would appreciate any insights to why this is failing. It is failing when I try using the following:

```bash
gem install pg -v '1.1.3' --source 'https://rubygems.org/' -- --with-pg-config=/Applications/Postgres.app/Contents/Versions/11/share/man/man1/pg_config.1 --with-pg-include=/Applications/Postgres.app/Contents/Versions/11/include
Building native extensions with: '--with-pg-config=/Applications/Postgres.app/Contents/Versions/11/share/man/man1/pg_config.1 --with-pg-include=/Applications/Postgres.app/Contents/Versions/11/include'
This could take a while...
ERROR:  Error installing pg:
	ERROR: Failed to build gem native extension.

    current directory: /Users/myaccount/.rvm/gems/ruby-2.5.1/gems/pg-1.1.3/ext
/Users/myaccount/.rvm/rubies/ruby-2.5.1/bin/ruby -I /Users/myaccount/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0 -r ./siteconf20181227-19103-jh08w0.rb extconf.rb --with-pg-config\=/Applications/Postgres.app/Contents/Versions/11/share/man/man1/pg_config.1 --with-pg-include\=/Applications/Postgres.app/Contents/Versions/11/include
Using config values from /Applications/Postgres.app/Contents/Versions/11/share/man/man1/pg_config.1

[snip]
```

**Comment by jakob** [comment]
Well, for a start, `/Applications/Postgres.app/Contents/Versions/11/share/man/man1/pg_config.1` is the man page about the pg_config script, not the pg_config script. The config script is in `/Applications/Postgres.app/Contents/Versions/11/bin/pg_config`

But typically, you don't need to provide `--with-pg-config` if your `$PATH` is configured correctly. See [the docs about configuring the $PATH](https://postgresapp.com/documentation/cli-tools.html)

Use the command `which pg_config` to check if the path is correctly. The expected output is `/Applications/Postgres.app/Contents/Versions/latest/bin/pg_config` or `/Applications/Postgres.app/Contents/Versions/11/bin/pg_config`.

You only need to provide `--with-pg-config` if you want to use a different pg_config than the one on your $PATH.

Furthermore, you don't need to provide `--with-pg-include`, since pg_config has that setting. `--with-pg-include` is only useful if you want to use a different include directory than the one defined in pg_config (you don't).

Last, but not least, I think on some OS versions you had to use `ARCHFLAGS="-arch x86_64" gem install pg`, but I don't think that is necessary if you use RVM.

**Comment by RustyHack** [comment]
Jakob thanks for the help and information, which will be helpful to know in the future. Soon after my post I found that I could use brew to install postresql which enabled me to build the pg gem. That solved the build problem and allowed my app to work again.
