### ISSUE TITLE
tablefunc

### ISSUE THREAD

**Issue by martinmueller39** [PostgresApp/PostgresApp#499]
Can I install tablefunc in the version of Postgres that I installed with your app. And if so, how

**Comment by anthonydb** [comment]
`CREATE EXTENSION tablefunc;` works on my install (PostgreSQL 11).

**Comment by tbussmann** [comment]
The [`tablefunc` extension](https://www.postgresql.org/docs/current/tablefunc.html) is part of the [core contrib modules](https://www.postgresql.org/docs/current/contrib.html) since [PostgreSQL 7.3 and was last updated in 9.4.1](https://why-upgrade.depesz.com/show?from=7.2&to=11.2&keywords=tablefunc). These modules are shipped with PostgresApp since ever I could reconstruct (at least 9.1). So it is not necessary to update Postgres(App) just to use this extension as you implied in #500

**Comment by martinmueller39** [comment]
Following the advice of somebody from the general Postgres list, I went to the command line and gave the command psql.  Then I used the command ‘\dx’, which I was told would produce a list installed extensions. Which it did in this response;


                 List of installed extensions

  Name   | Version |   Schema   |         Description

---------+---------+------------+------------------------------

 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language

(1 row)

The related command \df+ *.crosstab*  has a similarly negative result.

In installing Postgres on my Mac I used the standard procedure of Postgres.app. It does not seem to be be case that my version of Postgres (10.5) includes the core contrib modules.

Or am I missing something?

**Comment by tbussmann** [comment]
The `psql` [meta command](https://www.postgresql.org/docs/current/app-psql.html#APP-PSQL-META-COMMANDS) `\dx` lists the _installed_ extensions based on [`pg_extension`](https://www.postgresql.org/docs/current/catalog-pg-extension.html). Try something like `SELECT * FROM pg_available_extensions;` to see what is [currently available](https://www.postgresql.org/docs/current/view-pg-available-extensions.html).

**Comment by jakob** [comment]
As @anthonydb said, you need to execute the command "CREATE EXTENSION tablefunc" to install it.
