### ISSUE TITLE
Add extension `postgis_sfcgal`

### ISSUE THREAD

**Issue by met-pub** [PostgresApp/PostgresApp#529]
\# SELECT PostGIS_Full_Version();
 POSTGIS="3.0.0beta1 r17835" [EXTENSION] PGSQL="120" GEOS="3.7.2-CAPI-1.11.2 b55d2125" PROJ="6.2.0" LIBXML="2.9.9" LIBPROTOBUF="1.3.2" WAGYU="0.4.3 (Internal)"
(1 row)

\# SELECT ST_GeomFromText('POLYGON (( 190 190, 10 190, 10 10, 190 10, 190 20, 160 30, 60 30, 60 130, 190 140, 190 190 ))');
0103...(omit)...6740
(1 row)

\# SELECT ST_ApproximateMedialAxis(ST_GeomFromText('POLYGON (( 190 190, 10 190, 10 10, 190 10, 190 20, 160 30, 60 30, 60 130, 190 140, 190 190 ))'));
ERROR:  function st_approximatemedialaxis(geometry) does not exist
LINE 1: SELECT ST_ApproximateMedialAxis(ST_GeomFromText('POLYGON (( ...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by bianbian-org** [comment]
https://postgis.net/2015/10/25/postgis_sfcgal_extension/
> postgis_sfcgal is not a default built extension when you build PostGIS.
Would you kindly please build PostGIS with postgis_sfcgal extension?

**Comment by jakob** [comment]
Looks like that has Boost as a dependency, just like pg_routing (see issue #288).

I don't see anything that would prevent us from including both of those extensions, but I haven't yet figured out how to work with Boost, and how to make sure everything that depends on boost builds in a way that's compatible with all the supported versions of macOS.

I have been meaning to have a look at this for some time, but I never got around to it. If you (or anyone else) can figure out the steps needed to build sfcgal (and pg_routing), and can add them to [this makefile](https://github.com/PostgresApp/PostgresApp/blob/master/src-12/makefile), I'd absolutely appreciate a pull request!

**Comment by steve-estes** [comment]
There are other default PostGIS extensions that aren't supported in your default package either, most particularly `address_standardizer` and its default rule dataset, `address_standardizer_data_us` .  Seems like if you're going to the trouble of enabling one you should enable the whole set of defaults, so that anyone following the enablement script on the right-hand side of [the PostGIS Install page](https://postgis.net/install/) won't get an error when it runs.

**Comment by rstrauss-logyx** [comment]
Please add SFCGAL.

**Comment by tbussmann** [comment]
Thanks for your feedback and interest on using `postgis_sfcgal` with PostgresApp. Adding this extension to the distribution is definitely on the ToDo list. 

Complementary compiling this on the users end for use with PostgresApp is not as feasible as it is with other extensions as this requires to recompile PostGIS which requires a load of dependencies itself. Given you have the necessary tools and libraries installed, you could try to rebuild the full package with your local installation of the `sfcgal` libraries by modifying the `Makefile` from the source tree of PostgresApp. But this is outside of what we are able to provide support for, I'm sorry to say.

**Comment by rstrauss-logyx** [comment]
Thanks tbussmann- I tried and failed to build src-11, but due to your message, tried again and failed again...

The first time, I got an error :
      configure: error: file 'tclConfig.sh' is required for Tcl

When I built sfcgal, it put the include and lib results into /usr/local/homebrew
So to the target:   postgis-${POSTGIS_VERSION}/GNUMakefile:
I added:   --with-sfcgal=/usr/local/homebrew
Your message jolted my brain and I removed (for good measure):
     with-libxslt --with-perl --with-tcl --with-python

Now, during linking, I get:
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      CPLRecodeIconv(char const*, char const*, char const*) in cpl_recode_iconv.o
      CPLRecodeFromWCharIconv(wchar_t const*, char const*, char const*) in cpl_recode_iconv.o
  "_iconv_close", referenced from:
      CPLRecodeIconv(char const*, char const*, char const*) in cpl_recode_iconv.o
      CPLRecodeFromWCharIconv(wchar_t const*, char const*, char const*) in cpl_recode_iconv.o
  "_iconv_open", referenced from:
      CPLRecodeIconv(char const*, char const*, char const*) in cpl_recode_iconv.o
      CPLRecodeFromWCharIconv(wchar_t const*, char const*, char const*) in cpl_recode_iconv.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libgdal.la] Error 1
make[1]: *** [check-lib] Error 2
make: *** [/Applications/Postgres.app/Contents/Versions/11/lib/libgdal.dylib] Error 2

Oh well...  I'll look for clues about this...

(Brew should be able to do it, but throws an error on my Mac when trying to build "pango" for python.
This seems to be a known issue with brew...)

**Comment by jakob** [comment]
Postgres.app 2.6.2 now ships with postgis_sfcgal (PG 15 only).
