### ISSUE TITLE
how to import shp flie in app

### ISSUE THREAD

**Issue by Tiramisupxl** [PostgresApp/PostgresApp#530]
HI，I am new in postgres。I have downloaded postgresApp  and pgAdmin4 in my mac。I want to know how to import shp file。I have searched on the Internet but found no anwser and I don‘t know what the difference or relatations between postgresSql、postgresApp and pgAdmin4。

**Comment by tmepple** [comment]
I would use `shp2pgsql` to import which is included in your installation of Postgres.app and documentation can be found online.  You can then use QGIS to visualize the shp map you imported.  

Since you are new to Postgres I would recommend reading the official documentation at https://www.postgresql.org/docs/current/ to understand the difference between the server and the client, etc.  Also the guides at http://postgresguide.com/ can help.

**Comment by anthonydb** [comment]
Hi, I hope this isn't too forward but I cover this extensively in my book "Practical SQL" for No Starch Press. All the code is online, so you can review some examples if you can't pick up the book.

Chapter 14 covers using PostGIS. Here's the code and data: https://github.com/anthonydb/practical-sql/blob/master/Chapter_14/Chapter_14.sql

In Chapter 16, on using the command line, I give some examples of loading shapefiles with `shp2pgsql` here: https://github.com/anthonydb/practical-sql/blob/master/Chapter_16/psql_commands.txt#L81

By the way, I promote using PostgresApp in the introduction of the book. It's fantastic. Cheers!

**Comment by jakob** [comment]
Thanks @tmepple and @anthonydb for the tips!
