### ISSUE TITLE
Upgrade did not make 11, 12 available

### ISSUE THREAD

**Issue by gisborne** [PostgresApp/PostgresApp#533]
Haven't run Postgres.app for a while. Ran it, expecting it would upgrade to a new version which would make v11 and v12 databases available, but while it upgraded and claimed to be the latest version when I asked it to check for upgrades, looking inside the package only showed 9 and 10 versions.

I had to download a new copy of Postgres.app to have access to 11 and 12.

**Comment by jakob** [comment]
Postgres.app does not automatically update across major versions. We do this to save bandwidth and disk space. One version of PostgreSQL takes around 200MB disk space, so we really don't want to download and install more than you need.

We should probably document that somewhere. If you want a new major version, you need to download a new version manually from postgresapp.com

**Comment by gisborne** [comment]
Maybe have a button in the app?

**Comment by jakob** [comment]
The changelist now includes info about the included versions of PostgreSQL, and a link to download different versions.

It's not perfect, since it doesn't tell users that other versions are available after upgrading to the latest version, but hopefully this will make it clear to users what's happening!
