### ISSUE TITLE
PostgreSQL 9.4 is not supported anymore

### ISSUE THREAD

**Issue by rhymes** [PostgresApp/PostgresApp#561]
I noticed the website contains info on installing PostgreSQL 9.4:

![Screenshot_2020-03-04 Postgres app Downloads](https://user-images.githubusercontent.com/146201/75884601-6d5f8980-5e25-11ea-9f87-541bc0ccb036.png)

This has been officially discontinued (other than emergency security updates) since February 13th, 2020:

![Screenshot_2020-03-04 PostgreSQL Versioning Policy](https://user-images.githubusercontent.com/146201/75884643-823c1d00-5e25-11ea-8c59-af5bd2f52ef7.png)

See <https://www.postgresql.org/support/versioning/>

**Comment by tbussmann** [comment]
9.4 had it's last/final release with the Feb. 2020 round of releases. Due to some issues, these were not published as PostgresApp here. As 9.4.26 was the final version for 9.4, I think it would make sense to release it, even if 9.4 is now EOL upstream. @jakob: Do you plan to exceptionally include 9.4.26 in the next round of releases scheduled for next week?

**Comment by jakob** [comment]
@tbussmann Yes, I plan on including the latest version of 9.4 in the build next week. I think I'll continue to include it until PostgreSQL 13 is released.

**Comment by jakob** [comment]
Okay, so just to clarify my plans:

Postgres.app will continue to include PostgreSQL 9.4 in the big download until the PostgreSQL 13 is released, to make it easier for those who still have a 9.4 database to migrate to a newer version.

Once we include PostgreSQL 13, we'll stop including PostgreSQL 9.4.
