### ISSUE TITLE
Postgres App Opens Every Boot-Up On Catalina; Ignores System and App Preferences

### ISSUE THREAD

**Issue by ProfStringer** [PostgresApp/PostgresApp#578]
_Note: At @jakob 's  request, I am opening a new ticket for a bug that is happening in Catalina.  The symptoms of this bug seem identical to those described in issue #407_ 

Symptom: 
Postgres App opens every boot up and there appears to be no way to hide it or make it go away.

Expected Behavior: 
When I de-select "Automatically start Postgres on Login" in the app preferences, I expect the Postgres app not to open on login.  

Actual Behavior:
The Postgres App window opens every launch.  It cannot be minimized, hidden, or otherwise made to go away without completely uninstalling the app.  [To be clear, I'm speaking of boot-up behavior.  Yes, I can manually quit the app once my system is launched.]  I need Postgres only occasionally, so my preference is to launch it and start it as needed.  Regardless of whether I want the server to start or not, why would I want that window to be dead center on my screen every boot up?  It's annoying as hell and I would expect this to behave like every other app on my mac and respect my preferences.

![PostgresAppOnStartup](https://user-images.githubusercontent.com/43785624/85558227-28d34600-b5ee-11ea-807f-d1650bcc23de.jpg)

Troubleshooting:
As suggested in issue #407, there are no launch agents for com.postgresapp in either ~/Library/LaunchAgents/ or in /[my drive]/Library/LaunchAgents. The only instance I found of the com.postgresapp.Postgres2LoginHelper.plist I found was in /Applications/Postgres/Contents/Resources/com.postgresapp.Postgres2LoginHelper.plist.  Moving this had no effect.

Even though the ticket said not to, I tried adding the Postgres app to my Login Items and marking it as hidden.  This had no effect.

The only way to make this window go away is to delete the app entirely.

Details:
![AboutThisMac](https://user-images.githubusercontent.com/43785624/85559091-00981700-b5ef-11ea-969f-2b93694e40bc.jpg)
Model Name:	iMac
  OS Version: 10.15.5 "Catalina"
  Model Identifier:	iMac18,3
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	3.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	64 GB
  Boot ROM Version:	183.0.0.0.0
  SMC Version (system):	2.41f2

Postgres App:
  Version 2.3.5 (79)

**Comment by jakob** [comment]
Thanks for the detailed bug report. This is not the intended behavior of Postgres.app.

To be honest, I have no idea why Postgres.app would launch after login. Do any other apps on your Mac do that?

Does Postgres.app also start when you log out (with Cmd-Shift-Q), and uncheck the "Reopen windows when logging back in" checkbox?

Do you have any other apps in your login items that might start Postgres.app for some reason?

After you quit Postgres.app, can you execute the following command in Terminal:
```
launchctl list | grep Postgres
```

(No agents except maybe `com.postgresapp.Postgres2LoginHelper` should show up for that command)

**Comment by ProfStringer** [comment]
See responses below...

> To be honest, I have no idea why Postgres.app would launch after login. Do any other apps on your Mac do that

No, I've never seen this behavior before on any of my macs.

> Does Postgres.app also start when you log out (with Cmd-Shift-Q), and uncheck the "Reopen windows when logging back in" checkbox?

Yes.  It reopens every time.  "Repopen" is unchecked.

> Do you have any other apps in your login items that might start Postgres.app for some reason?

No.  Or, more specifically, not that I can find.

> After you quit Postgres.app, can you execute the following command in Terminal:
>
> `launchctl list | grep Postgres`
> (No agents except maybe com.postgresapp.Postgres2LoginHelper should show up for that command)

These two are:

```
2356	0	com.postgresapp.Postgres2MenuHelper.11992
-	0	com.postgresapp.PostgresHelper

```
Maybe these are some vestigial hold-overs from a previous version?

**Comment by jakob** [comment]
Yes, this looks like it could cause the issue! I think the old PostgresHelper (com.postgresapp.PostgresHelper) started the main app. We previously used the LSRegister API to register the helper, but switched to using Launch Agents in Postgres.app 2 because they were easier to deal with.

The old helper is probably what's launching Postgres.app on login.

I'm not sure what the best way to remove the helper is. There are two ways in which you should be able to fix this:

1) Delete all old versions of Postgres.app from your computer. The helper app is inside the app package. If the old helper is gone, macOS can't launch it.

If you don't want to delete old versions of Postgres.app, you can try the following:

1) Quit the new Postgres.app

2) Remove the new Postgres.app from /Applications

3) Install an old version of Postgres.app (eg. Legacy Postgres.app with PostgreSQL 10 from here: https://postgresapp.com/downloads_legacy.html)

4) Open preferences in the legacy Postgres.app

5) Uncheck the "Start at Login" option

6) Quit Legacy Postgres.app

7) Remove legacy Postgres.app from /Applications and put the new one back

I hope this fixes the issue.
