### ISSUE TITLE
PostgresApp on Apple Silicon

### ISSUE THREAD

**Issue by dgdosen** [PostgresApp/PostgresApp#596]
Will this run natively? via Rosetta 2?

**Comment by jakob** [comment]
We've tested Postgres.app on a DTK, and it works fine with Rosetta 2. 

We will offer a universal binary eventually, but since Postgres.app has so many dependencies, it will take us a while. For some libraries making universal builds is trivial, we just need to build with different compiler flags. But eg. for OpenSSL we've had to patch some config files to make universal builds. It's probably safer to wait for these projects to officially support Apple Silicon.
