### ISSUE TITLE
App does not allow to run from other directories than /Applications

### ISSUE THREAD

**Issue by julian-weinert** [PostgresApp/PostgresApp#601]
There is no reason for these restrictions in my opinion.

![Screenshot 2020-12-16 at 14 04 10](https://user-images.githubusercontent.com/3418452/102352018-a0839b80-3fa7-11eb-952a-bc232a88f5ab.png)

**Comment by jakob** [comment]
I'd love it if Postgres.app was relocatable, but I just don't think it's going to work.

I tried to explain in previous issues #469 and #562.

The problem is that all the libraries use absolute paths, in order to allow linking other things against libraries provided by Postgres.app. Postgres.app itself would work fine with relative paths, but a lot of other things would no longer work with Postgres.app if we switched to @loader_path or @rpath.

Maybe there is a way to make it work, but I have tried a lot of things and haven't found a way to make it work, and nobody else has come up with a solution yet either.

**Comment by julian-weinert** [comment]
Oh darn. Sorry for not searching the issues good enough and thanks for clarification

**Comment by jakob** [comment]
We should probably add some explanation to the docs somewhere, since the issue comes up again and again. Github issue search is only useful if you know what you are looking for :)

I'm curious, could you explain why you were looking to run Postgres.app from another directory?

**Comment by julian-weinert** [comment]
You're absolutely right.
I'm often running Applications from disk images directly if I didn't decide to this particular software yet.
That's how I stumbled across the "issue".
Also I regularly come across people having Applications installed in the user directory, for example if the admin account is not available.
So there is a small potential road block for some people, but I would also think that this wouldn't apply to many developers actually ;-)
