### ISSUE TITLE
Application Support files safely deletable?

### ISSUE THREAD

**Issue by jessemorton** [PostgresApp/PostgresApp#622]
Thanks for the great app. I've used it for years and have accumulated a ~25 >1GB files beneath Application Support that have no file extension with them, that I'm wondering whether I can safely delete. My database isn't 25 GB, and if they're backups of some sort, I'd prefer not to keep dozens.

<img width="569" alt="big file" src="https://user-images.githubusercontent.com/914094/114194991-a7973680-9915-11eb-9c4a-037173ffb262.png">

**Comment by tbussmann** [comment]
Be careful: These files actually _are_ your database (or at least they belong to _a_ PostgreSQL cluster), you should better not delete them. To verify these belong to the database/cluster/server you refer to, please press the "Server Settings..." button in PostgresApp and compare the path (up to "var-11") to the value listed under "Data Directory". In general, there is hardly anything within the data directory that can safely be modified directly (except `.conf` files) or deleted (except `.log`, `./log/` - do not confuse with `./pg_xlog/` in pg < 10!).

If you think the files are way bigger then the expected size of your database (keep in mind that not only the data itself but also their indexes contribute to the size of a database), this is likely a result of updates or deletions that happened over time (an effect called 'bloat'). To reclaim the free space, you can run a [`VACUUM FULL`](https://www.postgresql.org/docs/current/sql-vacuum.html) on the database. For this simply connect to the database in `psql`(eg. by double clicking on the database icon in PostgresApp) and enter `VACUUM FULL;` depending on the size of the database this process my take a while. This requires exclusive access on the tables, so make sure there are no concurrent writing transactions open, otherwise the process will wait for them to finish. 

Within `psql` you can also get a quick overview on the size of the databases in your cluster using the meta command `\l+` or `\dt+`/`\di+` for a drill-down per table/index. If you have lot's of bloat, you will notice these values decrease significantly after a `VACUUM FULL`. At the same time, you will notice a reduction of the files / their sizes in Finder in the directory mentioned initially.

**Comment by jessemorton** [comment]
Appreciate the speedy and informative response @tbussmann. Via `\l+` I'm making better sense of the size of things. Though very oddly, I did the `VACUUM FULL` and my HD available space actually _went down_ by 13 GB, which didn't make sense. But I was able to watch available space on the HD rapidly decreasing during the course of the command getting run, expecting it rather to increase of course. This seems outside the scope of PostgresApp's bug ticketing, so I won't expect you to solve this oddity for me, though if you're in the mood, any tips welcome. Thanks again.

**Comment by tbussmann** [comment]
glad I could be of help here. 

> But I was able to watch available space on the HD rapidly decreasing during the course of the command getting run, expecting it rather to increase of course.

An increase in disk usage during the vacuum process is actually expected as the command is internally coping the still-valid data into fresh and not fragmented files before deleting the originals.

> and my HD available space actually went down by 13 GB

That indeed makes no sense. The size of of the data directory should decrease (or stay approx. the same) _after_ the `VACUUM FULL` is completed. Keep in mind that the concept of 'available space' on an APFS volume is always a question of perspective (think sparse files, clones, snapshots, volumes sharing a container). In this case, there may still be local TimeMachine snapshots containing the previous versions of these files. You can have a look to the 'available' and 'used' figures in Finder's 'Get Info' window of the volume, in Disk Utility and System Information. Look for 'reclaimable', 'hidden' or 'purgeable' values. Usually, macOS will take care of this automatically over time and reclaim this space once more is needed. You can find endless considerations on this topic on google - if you are after a deep dive, I'd recommend the [blog of Howard Oakley](https://eclecticlight.co/tag/apfs/) as a good start.

**Comment by jessemorton** [comment]
The Get Info window is what was originally showing a larger available space, and 13GB smaller after `VACUUM FULL` (with less than 1 GB purgeable), so that's why I thought it was so odd. 

But your mention of taking a look at Disk Utility pointed me to the different perspective that probably makes sense of things: 2 volumes show up there, "Macintosh HD" (with the small space number), while the "Macintosh HD - Data" volume shows that number plus  20 GB more (and 20.09 GB purgeable). Thanks @tbussmann, much appreciated.
