### ISSUE TITLE
queries slower than expected

### ISSUE THREAD

**Issue by miguelscarv** [PostgresApp/PostgresApp#649]
I'm running a project that needs to get data in real time. before, when I ran the project on my intel with mysql, everything ran really fast, pretty much instantaniously, but with my m1 pro and this postgres app queries take 30x more than on mysql.

Is it because this is a lightweight version of postgres, because I'm on a m1...?

**Comment by jakob** [comment]
It's impossible to say why your queries are slower on one system than on another without any information about the database schema or the type of queries you are executing.

> Is it because this is a lightweight version of postgres, because I'm on a m1...?

No. Postgres.app is a full featured PostgreSQL installation, and it performs very well on M1 processors.

**Comment by jakob** [comment]
I'm closing this issue since there is not enough information to give any advise.

If you don't tell us what query you are running and what your databases schema looks like, there is no way we can tell you why it is slow. My first guess would be that you have a missing index somewhere, but there are a hundred other things that could be the problem and it's pointless to make guesses without more info.

If you want to get help, please open a new issue with more details.

Also, we're not a general PostgreSQL support forum, there are other places were you can get better advise on PostgreSQL.
