### ISSUE TITLE
Have you considered offering a paid version for businesses to help support the project?

### ISSUE THREAD

**Issue by rathboma** [PostgresApp/PostgresApp#650]
Hey team,

I used Postgres app heavily when I worked on a Rails app on a Mac, so did the whole engineering team.

Have you considered offering a paid version of the app with extra features / paid support? Feels like a lot of businesses depend on the app.

If not - can I ask why?

**Comment by jakob** [comment]
Our goal with Postgres.app is to make it so that our users don't need support. I doubt there are many people who would need support for Postgres.app specifically.

Most of the things people need help with are not specific to Postgres.app, people usually need help with general PostgreSQL topics. There are a lot of companies that offer commercial support for PostgreSQL, and they could probably help you with Postgres.app troubles as well.

As for a paid version with more features, I just don't really have an idea what we should put in a paid version.

I also like the fact that Postgres.app is free and everyone can use all the features.
