### ISSUE TITLE
_postgres User

### ISSUE THREAD

**Issue by Gramarin** [PostgresApp/PostgresApp#659]
Hi, I was just wondering whether installation of PostgreSQL on Mac using the .app adds the _postgres service user or is that user present by default on MacOS? Should I delete this user when uninstalling PostgreSQL.app?

**Comment by jakob** [comment]
Postgres.app runs with your user. It does not create a separate OS user for PostgreSQL.

There's no need to delete the extra user account to use Postgres.app

Some installers create a separate user for PostgreSQL, maybe you installed a different PostgreSQL distribution before?

**Comment by tbussmann** [comment]
adding to that, `_postgres` was a default systemuser provided by Apple in earlier versions of OS X. I just checked OS X 10.9 where it is still provided. Apple sometime got rid of it at or before macOS 10.12 likely around the time they stopped shipping outdated PostgreSQL (client) libraries. Further, the "macOS Server" App contained (contains?) a PostgreSQL package even longer and creates a `_postgres` user even on newer OS.

**Comment by Gramarin** [comment]
I don't remember whether I installed it before in some other way. I don't think so.
I just had a chat to Apple Support and they seem to be confident that MacOS comes with PostgreSQL and it runs in the menu bar. Not sure where/how that works.
I want to remove the .app and install via homebrew and start the app under the user _postgres service user which is best practice from a security standpoint. But I'm not sure whether I can use the apparently default _postgres to start PostgreSQL or whether I should create another user.

**Comment by jakob** [comment]
I just checked, and my new Macbook also has a `_postgres` system user. It seems that macOS creates this user by default. You can't login as that user since its shell is `/usr/bin/false`. I'm not sure using it is actually a good idea, it's probably just a historic artefact.

AFAIK, Homebrew also runs PostgreSQL under your user by default, whereas Macports and the EDB installer create a new user named `postgres` (without underscore) and use that to run PostgreSQL.

Using a separate user to run the PostgreSQL server is standard practice on servers that accept network connections, but I don't consider it necessary if you are just going to use the PostgreSQL server locally and don't allow untrusted users on your system.

**Comment by Gramarin** [comment]
Yer, I'm not sure about that _postgres account either. I don't want to modify it in any way in case it's used somewhere that I'm not aware of. From what I read, there's no difference between service and user accounts so theoretically it should be ok to log into it by changing the /usr/bin/false field, but yes, just don't know.

I think the way it works is, you `sudo su postgres` and then run the `pg_ctl ... start` under that user. That way you're running the Homebrew version as the dedicated user.

Thanks for the enlightenment about Macport and EDB versions creating a postgres user.

Yer I don't intend to use it over the internet, so running it through the .app should probably be fine for my home server. But I'm doing this partly as an education exercise also. Discovering many blindspots!
