### ISSUE TITLE
Revert to 12.9 possible because of 12.10 bug?

### ISSUE THREAD

**Issue by dyve** [PostgresApp/PostgresApp#663]
There seems to be a nasty bug in Postgres 12.10:

- https://stackoverflow.com/questions/71126845/how-to-fix-internalerror-variable-not-found-in-subplan-target-list
- https://www.postgresql.org/message-id/2121219.1644607692%40sss.pgh.pa.us

Is there any way to revert to 12.9 using Postgres.app?

**Comment by jakob** [comment]
The latest build with 12.9 is this one: https://github.com/PostgresApp/PostgresApp/releases/tag/v2.5.5

You should be able to just quit Postgres.app, replace the app in /Applications with the old build, and start it again. Minor version up-/downgrades usually just work, but you can check the release notes for details.

**Comment by jakob** [comment]
For future reference: You can find a list of available builds here: https://github.com/PostgresApp/PostgresApp/blob/master/BUILD_HISTORY.md

And you can download all the past releases here:
https://github.com/PostgresApp/PostgresApp/releases

It seems that the fix was included in git commit 32e801676b1ef821c6ee308f7ea42386a3e15768, so the problem should be fixed in 12.11, which is scheduled to be released on May 12, 2022

**Comment by dyve** [comment]
Thanks @jakob. This worked for me. Much appreciated.

**Comment by tbussmann** [comment]
@dyve: the error was fixed upstream and is included in the recent May 2022 releases v2.5.7 of PostgresApp in all supported versions of PostgreSQL. From the [release notes](https://www.postgresql.org/docs/release/)

> - Fix plan generation for index-only scans on indexes with both returnable and non-returnable columns (Tom Lane)
> The previous coding could try to read non-returnable columns in addition to the returnable ones. This was fairly harmless because it didn't actually do anything with the bogus values, but it fell foul of a recently-added error check that rejected such a plan.
