### ISSUE TITLE
PG 14 binaries no longer include geos.h

### ISSUE THREAD

**Issue by jakob** [PostgresApp/PostgresApp#667]
I'm not sure how serious this issue is, but I saw that geos.h is no longer in 14/include/geos.h

I believe this is caused by the change from make to cmake when building GEOS (in this commit: a83e6f18d07f1b69d8011b50a01880350d6c0175)

For the 2.5.7 releases, I just copied geos.h from an old build.

I'm not sure if anyone actually needs this file, but I think it won't do any harm to add it.

**Comment by tbussmann** [comment]
indeed, `geos.h` is no longer installed when building with `cmake` which is the only supported version since geos 3.10.0. As it is still mentioned in the readme I'd see this as a bug and will try to submit an upstream patch.
> For the 2.5.7 releases, I just copied geos.h from an old build.
that should work if you are referring to an old build of our pg14 tree which previously included geos 3.9.x - the structure of includes within `geos.h` changed between geos 3.8.x (used in our pg13 builds) and geos 3.9.x, but not later.
> I'm not sure if anyone actually needs this file, but I think it won't do any harm to add it.
me neither. If I understand it correctly, this header is a shortcut to use the C++ bindings which are not stable between releases anyhow...

**Comment by jakob** [comment]
> that should work if you are referring to an old build of our pg14 tree which previously included geos 3.9.x

Yes, that's what I did.

**Comment by tbussmann** [comment]
> submit an upstream patch.

For reference, that upstream PR is https://github.com/libgeos/geos/pull/607
