### ISSUE TITLE
initial setup steps to use default postgres user not system user

### ISSUE THREAD

**Issue by pstephenwille** [PostgresApp/PostgresApp#700]
Using the systems user name has created confusion and extra work, and put me out of sync with instructions for other apps.
I would prefer if the setup steps started the services and initialized the db with the postgres user

**Comment by tbussmann** [comment]
Not sure, I fully understand your issue. 

Postgres.app _does_ name the default superuser during initialisation `postgres` since PostgreSQL 9.5 in 2015. It does create an _additional_ superuser named after the current user and database owned by that for easy access (ref https://github.com/PostgresApp/PostgresApp/issues/275#issuecomment-156358749). If you don't want these, you can still drop them but the GUI won't be able to display the databases in that case. For full control over all options, you can still run `initdb` on your own. Refer to the [Readme](https://github.com/PostgresApp/PostgresApp#under-the-hood) for details on the commands.
