### ISSUE TITLE
Why administrator rights are needed for installation?

### ISSUE THREAD

**Issue by kyzmitch** [PostgresApp/PostgresApp#734]
Wasn't able to find answer for this question. Usually it is not safe to give root/admin rights to the app

**Comment by jakob** [comment]
I believe administrator rights are needed to move anything into the Applications folder. Postgres.app does not need admin rights.

With recent changes, you no longer need to copy Postgres.app into the applications folder (see issue #693), and you can launch it from other locations.

**Comment by kyzmitch** [comment]
I see that the latest installer requires administrator password before installation, and there is no install dir selection before that. Anyway I found similar app which doesn't require additional rights

**Comment by jakob** [comment]
It sounds like you are using a different PostgreSQL distribution and not Postgres.app. Postgres.app does not need admin permissions.

You can download Postgres.app from here: https://postgresapp.com

Since you are talking about an installer, maybe you are talking about the EnterpriseDB installer? The EnterpriseDB installer needs an admin password because it creates a separate user account for the PostgreSQL server.

In any case, this Github repo is about Postgres.app, and since it sounds like you aren't using Postgres.app, I'm closing this issue!
