### ISSUE TITLE
Update Error! Try again later.

### ISSUE THREAD

**Issue by tmcsys** [PostgresApp/PostgresApp#755]
Update Error!

An error occurred in retrieving update information. Please try again later.

Postgresapp 2.6.2 PostgreSQL 15
MacOS Ventura 13.6 Intel

I’d like to update Postgis to get the 3.4 debug_standardize_address function

I believe this is the first time I’ve tried to install updates so it could be permissions.

Any ideas would be appreciated.

**Comment by tbussmann** [comment]
I just tried the automatic update from Postgres-2.6.2-15 to the latest version 2.7.1. For me it works well. If it doesn't for you, you can always download new versions directly from https://postgresapp.com/downloads.html or https://github.com/PostgresApp/PostgresApp/releases, mount the .dmg and drag the new version of Postgres.App to your Application folder.

However, `debug_standardize_address()` is a function that is available since PostGIS 3.4. We bundle PostGIS 3.4.x with PostgreSQL 16 only. To use this function, you can either start with a fresh PostgreSQL 16 server or upgrade your PostgreSQL 15 database to PostgreSQL 16. The easiest way to do this is to download "Postgres.app with all currently supported versions" from the link above and follow the `pg_dumpall` instructions given at  https://postgresapp.com/documentation/migrating-data.html

**Comment by tmcsys** [comment]
Thank you for your rapid and comprehensive reply.

You can close this ticket.

My Mac was having more problems than just the PostgresApp update.  After I restarted the update ran without any problem. (Ventura has been so reliable I tend to suspect Apps before I question it.)

I will look into a Postgres 16 migration.  The address standardizer appears to be something of a black art.  I hope to shed some light on it with the debug function.

And thank you for helping to make Postgres/Postgis accessible to those of us with Macs.
