### ISSUE TITLE
postgreSQL downloard error 

### ISSUE THREAD

**Issue by jangdaeunnn** [PostgresApp/PostgresApp#761]
during the download PostgreSQL, I faced a problem. the warning message that is written in 'psql : (strange language) "localhost1" (strange language)"Unknown host' pop up. in this case, what should I do to download successfully?

**Comment by jangdaeunnn** [comment]
Help me... I'm not good at English...but I hope you guys know what I'm saying....

**Comment by jakob** [comment]
It sounds like your issue is unrelated to Postgres.app. We do not offer generic PostgreSQL support.

Maybe you can find help in Korean on one of these sites:

- https://www.postgresql.org/community/international/

- https://database.sarang.net/?criteria=pgsql

- https://www.facebook.com/groups/postgres.kr/
