### ISSUE TITLE
Existing data directory found during postgres installation

### ISSUE THREAD

**Issue by Alli-Grace** [PostgresApp/PostgresApp#762]
An existing data directory has been found at C:\Program Files\PostgreSQL\16\data set to use port number 5432. This directory and its configuration will be used for this installation.

This is what I've been getting while installing a new postgres and i think it is the related to the connection error I'm getting while opening pgadmin.
This is the error I'm getting after going through the installation like that and opening pgadmin

(Please enter the password for the user 'postgres' to connect the server - "PostgreSQL 16"
connection timeout expired)

I've tried uninstalling the existing postgres in control panel and app and features

Please what can i do in this case

**Comment by jakob** [comment]
Hi! It sounds like you are trying to install PostgreSQL on Windows. We don't offer support for Windows here. 
This Github project is for Postgres.app, a Mac app for installing PostgreSQL.

If you are using the EnterpriseDB installer for Windows, please contact EnterpriseDB for support. Otherwise, you can check the [PostgreSQL mailing lists](https://www.postgresql.org/list/) for general PostgreSQL questions.
