### ISSUE TITLE
pl/python

### ISSUE THREAD

**Issue by mietennet** [PostgresApp/PostgresApp#767]
Hi,

i had the need to use pl/python and read this:

[https://postgresapp.com/documentation/plpython.html](https://postgresapp.com/documentation/plpython.html)

but after pooking around a bit if found it will work with my already installed homebrew version after this:

sudo ln -s /usr/local/Frameworks/Python.framework /Library/Frameworks/

Is something wrong with that solution? If not i would send pull request for the page mention above!

greetings

**Comment by jakob** [comment]
> Is something wrong with that solution?

It may accidentally work, or it may not work. We don't test it. To be honest, I am surprised that it does work.

According to the docs, PL/Python needs to be linked  with a specific version of Python. We link it with the documented versions of Python, and can guarantee that it works if you install that version.

If you install the same Python version with Homebrew, your trick might work. But we don't test it, and we can't guarantee that it works, and since Homebrew tends to automatically upgrade to newer versions, it might suddenly stop working.

If it works for you, I don't see a problem with it. But it's not something we would recommend in general.
