### ISSUE TITLE
No setting preventing PostgresApp to appear in the status menu on every boot

### ISSUE THREAD

**Issue by tgdn** [PostgresApp/PostgresApp#768]
Every time my computer boots, the PostgresApp icon appears in the status menu.

Running `launchctl list | grep Postgres` returns the following:

```
application.com.postgresapp.Postgres2MenuHelper.22889707.22889713
application.com.postgresapp.Postgres2.22889421.22889706
com.postgresapp.Postgres2LoginHelper
```

Apart from manually removing them using `launchctl remove [name]` I see no other way to do so in the settings. Where `[name]` is one of the listed items above.

Is this the default behavior?

Version 2.7.6 (270)
macOS Sonoma 14.3

**Comment by jakob** [comment]
How about this setting in Postgres.app preferences?

<img width="694" alt="Bildschirmfoto 2024-09-16 um 09 46 39" src="https://github.com/user-attachments/assets/c1562f1e-4a1a-43cb-8f6f-5705f395f509">

**Comment by tgdn** [comment]
Perhaps I misunderstand what it means, but doesn't this only "hide" the icon? Something is still running in the background?

The idea would be to have fewer programs running in the background while not in use - so not starting at all, rather than starting and hiding the fact that it's running.

**Comment by jakob** [comment]
When the menu bar status item is hidden, the only thing that runs in the background are PostgreSQL servers that are configured to start automatically. If you don't want servers to start at login, you can disable this in the per server settings.

Postgres Login Helper is a tool that runs once at login, checks if servers are configured to start automatically or if the menu bar helper needs to be launched, and then quits again. It does not keep running.

If you don't want Postgres.app to launch anything at all when logging in, please use the new "Login Items" section in the system settings app.

(When running on older versions of macOS, there is a "launch at login" checkbox inside the Postgres.app preferences. But this checkbox is hidden on newer versions of macOS because it would conflict with system setting)

**Comment by tgdn** [comment]
Very clear, thank you!
